name: Update Banners

on:
  pull_request:
    types:
      - closed

jobs:
 
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.4
        bundler: "Gemfile.lock"
        bundler-cache: true
    - name: Update banners
      run: |
        ruby -e "require './lib/live_log/version'; p LiveLog::VERSION" | xargs -I curr sh -c "sed s/%{version}/curr/g  .github/workflows/banners/gem_version.svg" >> .github/banners/gem_version.svg
        ruby -e "require 'json'; p JSON.parse(File.read('./coverage/.last_run.json'))['result']['line']" | xargs -Ish -c 'sed s/%{coverage}/curr/g .github/workflows/banners/coverage.svg' >> .github/banners/coverage.svg
        git rev-parse --abbrev-ref HEAD | xargs -I curr sh -c "sed s/%{branch}/curr/g .github/workflows/template.md" >> README.md

      