name: RSpec Coverage

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: --entrypoint redis-server
    env:
      RAILS_ENV: test
      GEMFILE_RUBY_VERSION: 2.7.2

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler: "Gemfile.lock"
          bundler-cache: true
      - name: Run tests
        run: |
          rspec
