name: RSpec Coverage

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: --entrypoint redis-server
    env:
      RAILS_ENV: test
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.4
          bundler: "Gemfile.lock"
          bundler-cache: true
      - name: Run tests
        run: |
          bundle exec rspec
      - name: Update banners
        run: |
          ruby -e "require_relative 'lib/live_log/version'; p LiveLog::VERSION" | xargs -I curr sh -c "sed s/%{version}/curr/g .github/workflows/banners/gem_version.svg  >> .github/banners/gem_version.svg"
          ruby -e "require 'json'; p JSON.parse(File.read('./coverage/.last_run.json'))['result']['line']" | xargs -I curr sh -c "sed s/%{coverage}/curr/g .github/workflows/banners/coverage.svg >> .github/banners/coverage.svg"
          git rev-parse --abbrev-ref HEAD | xargs -I curr sh -c "sed s/%{branch}/curr/g .github/workflows/template.md" >> README.md




